// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gin-gonic/gin"
	"stock-ai/internal/adapter"
	"stock-ai/internal/api/handler"
	"stock-ai/internal/api/router"
	"stock-ai/internal/backtest"
	"stock-ai/internal/config"
	"stock-ai/internal/datacollect"
	"stock-ai/internal/indicator"
	"stock-ai/internal/model"
	"stock-ai/internal/monitor"
	"stock-ai/internal/notifier"
	"stock-ai/internal/subscription/quotecache"
	"stock-ai/internal/subscription/runner"
	"stock-ai/internal/subscription/scheduler"
)

// Injectors from wire.go:

// InitializeApp 由 wire 生成完整组件图。
// cfg 由 main() 加载后传入，wire 将其注入到 App.Config 字段。
func InitializeApp(cfg *config.Config) (*App, error) {
	registry := provideRegistry()
	quoteCache := quotecache.NewQuoteCache(registry)
	stockSourceProvider := quotecache.NewCachedQuoteProvider(quoteCache)
	quoteSubscriber := provideQuoteSubscriber(quoteCache)
	v := handler.AllBuiltins()
	indicatorRegistry := indicator.NewRegistry(v)
	engine := provideEngine(indicatorRegistry)
	notifierNotifier := notifier.NewNotifier()
	subscriptionRunner := runner.NewSubscriptionRunner(stockSourceProvider, engine, notifierNotifier)
	schedulerScheduler := scheduler.NewScheduler(subscriptionRunner)
	dataCollectRunner := datacollect.NewDataCollectRunner()
	datacollectScheduler := datacollect.NewScheduler(dataCollectRunner)
	service := backtest.NewService(engine)
	backtestHandler := backtest.NewHandler(service)
	monitorMonitor := monitor.NewMonitor(quoteSubscriber, notifierNotifier)
	ginEngine := provideRouter(dataCollectRunner, backtestHandler)
	app := &App{
		Config:        cfg,
		Registry:      registry,
		QuoteCache:    quoteCache,
		StockProvider: stockSourceProvider,
		QuoteSub:      quoteSubscriber,
		IndicatorReg:  indicatorRegistry,
		Engine:        engine,
		Notifier:      notifierNotifier,
		SubRunner:     subscriptionRunner,
		SubScheduler:  schedulerScheduler,
		DCRunner:      dataCollectRunner,
		DCScheduler:   datacollectScheduler,
		BtService:     service,
		BtHandler:     backtestHandler,
		Monitor:       monitorMonitor,
		Router:        ginEngine,
	}
	return app, nil
}

// wire.go:

func provideRegistry() *adapter.Registry {
	return adapter.GetRegistry()
}

func provideQuoteSubscriber(cache quotecache.QuoteCache) model.QuoteSubscriber {
	return cache.Subscriber()
}

func provideEngine(reg *indicator.Registry) *indicator.Engine {
	return reg.Engine()
}

func provideRouter(dcRunner *datacollect.DataCollectRunner, btHandler *backtest.Handler) *gin.Engine {
	router.BacktestHandlerRef = btHandler
	return router.SetupRouter(dcRunner)
}
